jQuery(document).ready(function(){
  jQuery("#p").click(function(){
    jQuery("#h").slideToggle();
  });
  jQuery("#a").click(function(){
    jQuery("#b").slideToggle();
  });
  jQuery("#c").click(function(){
    jQuery("#d").slideToggle();
  });
  jQuery("#e").click(function(){
    jQuery("#f").slideToggle();
  });
  jQuery("#g").click(function(){
    jQuery("#i").slideToggle();
  });
  jQuery("#j").click(function(){
    jQuery("#k").slideToggle();
  });
  jQuery("#l").click(function(){
    jQuery("#m").slideToggle();
  });
  jQuery("#n").click(function(){
    jQuery("#o").slideToggle();
  });
  jQuery("#q").click(function(){
    jQuery("#r").slideToggle();
  });
  jQuery("#s").click(function(){
    jQuery("#t").slideToggle();
  });
  jQuery("#u").click(function(){
    jQuery("#v").slideToggle();
  });
  jQuery("#rt").click(function(){
    jQuery("#w").slideToggle();
  });
  jQuery("#x").click(function(){
    jQuery("#y").slideToggle();
  });
  jQuery("#aa").click(function(){
    jQuery("#bb").slideToggle();
  });
  jQuery("#cc").click(function(){
    jQuery("#dd").slideToggle();
  });
  jQuery("#ee").click(function(){
    jQuery("#ff").slideToggle();
  });
  jQuery("#gg").click(function(){
    jQuery("#hh").slideToggle();
  });
  jQuery("#ii").click(function(){
    jQuery("#jj").slideToggle();
  });
  jQuery("#kk").click(function(){
    jQuery("#ll").slideToggle();
  });
});
